### PR TITLE
Style: Improve lookbook layout 1. clip upper part of a long image 2. display the middle part of a wide image

### PR DESCRIPTION
**Pull request by x-tropy**

### CODE REVIEW

**Review by nerdinand — APPROVED** [review]
Looks great, thanks!

**Comment by nerdinand** [comment]
@x-tropy feel free to merge. My policy is that whoever opened the PR should get to push the button, once it is approved ;)

**Comment by x-tropy** [comment]
Is this feature launched automatically after the merge?

**Comment by nerdinand** [comment]
No, i need to deploy manually, but I'm doing it right now!

**Pull request merged**
